"""test running migrations

Revision ID: 6e9f2701df2b
Revises: dfaf383683f2
Create Date: 2023-02-07 21:58:51.679664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9f2701df2b'
down_revision = 'dfaf383683f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
