"""test running migrations

Revision ID: 95d949e5ed7d
Revises: c8cb057ab396
Create Date: 2023-02-07 20:46:19.377999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d949e5ed7d'
down_revision = 'c8cb057ab396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
