"""test running migrations

Revision ID: c8cb057ab396
Revises: c25800141d5a
Create Date: 2023-02-07 20:40:00.936469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cb057ab396'
down_revision = 'c25800141d5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
