"""test running migrations

Revision ID: dfaf383683f2
Revises: 95d949e5ed7d
Create Date: 2023-02-07 21:01:02.348767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfaf383683f2'
down_revision = '95d949e5ed7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
